# Generated by Django 4.2.6 on 2023-10-23 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0011_alter_comment_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author_post',
            new_name='parent_post',
        ),
    ]
