# Generated by Django 4.2.6 on 2023-10-24 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0013_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='parent_post',
            new_name='parent_comment',
        ),
    ]
