# Generated by Django 4.2.6 on 2023-11-23 14:44

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):
    dependencies = [
        ("a_users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format=None,
                keep_meta=True,
                null=True,
                quality=85,
                scale=None,
                size=[600, 600],
                upload_to="avatars/",
            ),
        ),
    ]
